# Generated by Django 5.2.11 on 2026-02-14 23:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('bark', 'bark')], max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('config_json_encrypted', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForwardingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('filter_json', models.JSONField(default=dict)),
                ('bark_payload_template_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beacon.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IngestEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('payload_text', models.TextField()),
                ('payload_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('headers_json', models.JSONField(default=dict)),
                ('query_json', models.JSONField(default=dict)),
                ('remote_ip', models.CharField(max_length=64)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ingest_endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beacon.ingestendpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('sending', 'sending'), ('retry', 'retry'), ('sent', 'sent'), ('failed', 'failed')], max_length=16)),
                ('attempt_count', models.IntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('provider_response_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beacon.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beacon.forwardingrule')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beacon.message')),
            ],
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['user', 'created_at'], name='beacon_chan_user_id_20b1fd_idx'),
        ),
        migrations.AddIndex(
            model_name='forwardingrule',
            index=models.Index(fields=['user', 'created_at'], name='beacon_forw_user_id_95e725_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestendpoint',
            index=models.Index(fields=['user'], name='beacon_inge_user_id_de2686_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user', 'received_at'], name='beacon_mess_user_id_28783c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user', 'ingest_endpoint', 'received_at'], name='beacon_mess_user_id_37b224_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='beacon_deli_status_8ebcb2_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['message'], name='beacon_deli_message_1c8ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['user', 'created_at'], name='beacon_deli_user_id_0ce6ca_idx'),
        ),
    ]
