# Generated by Django 5.2.11 on 2026-02-15 17:56

from django.db import migrations


def _forward(apps, schema_editor):
    ForwardingRule = apps.get_model("beacon", "ForwardingRule")

    for r in ForwardingRule.objects.filter(payload_template_json__isnull=True):
        tpl = getattr(r, "bark_payload_template_json", None)
        if isinstance(tpl, dict) and tpl:
            r.payload_template_json = tpl
            r.save(update_fields=["payload_template_json"])


def _reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("beacon", "0002_forwardingrule_payload_template_json"),
    ]

    operations = [
        migrations.RunPython(_forward, _reverse),
    ]
