# Generated by Django 5.2.6 on 2026-02-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beacon", "0005_ingestendpoint_deleted_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="payload_text",
            new_name="body",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="payload_sha256",
            new_name="body_sha256",
        ),
        migrations.AddField(
            model_name="message",
            name="title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="group",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="priority",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="message",
            name="tags_json",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="message",
            name="url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="extras_json",
            field=models.JSONField(default=dict),
        ),
        migrations.RemoveField(
            model_name="forwardingrule",
            name="bark_payload_template_json",
        ),
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="message",
            name="received_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["user", "group"], name="beacon_mess_user_id_ddf4e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["user", "priority"], name="beacon_mess_user_id_6eb1f7_idx"
            ),
        ),
    ]
