# Generated by Django 5.2.6 on 2026-02-19 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0006_v1_breaking_schema"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="message",
            new_name="beacon_mess_user_id_67c862_idx",
            old_name="beacon_mess_user_id_ddf4e8_idx",
        ),
        migrations.RenameIndex(
            model_name="message",
            new_name="beacon_mess_user_id_065d41_idx",
            old_name="beacon_mess_user_id_6eb1f7_idx",
        ),
    ]
