# Generated by Django 5.2.11 on 2026-02-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forwardingrule",
            name="payload_template_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
