# Generated by Django 5.2.11 on 2026-02-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0003_backfill_payload_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="type",
            field=models.CharField(
                choices=[("bark", "bark"), ("ntfy", "ntfy"), ("mqtt", "mqtt")],
                max_length=16,
            ),
        ),
    ]
