"""
Django settings for beacon_spear project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from typing import Any, cast
from urllib.parse import parse_qs, unquote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _parse_database_url(url: str) -> dict[str, Any]:
    parsed = urlparse(url)
    scheme = (parsed.scheme or "").split("+", 1)[0].lower()

    if scheme in {"postgres", "postgresql"}:
        name = unquote((parsed.path or "").lstrip("/"))
        out: dict[str, Any] = {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": name,
            "USER": unquote(parsed.username or ""),
            "PASSWORD": unquote(parsed.password or ""),
            "HOST": parsed.hostname or "",
            "PORT": str(parsed.port or ""),
            "CONN_MAX_AGE": 60,
        }
        qs = parse_qs(parsed.query or "")
        sslmode = (qs.get("sslmode") or [""])[0]
        if sslmode:
            out.setdefault("OPTIONS", {})
            out["OPTIONS"]["sslmode"] = sslmode
        return out

    if scheme in {"sqlite", "sqlite3"}:
        path = unquote(parsed.path or "")
        if path in {":memory:", "/:memory:"}:
            name = ":memory:"
        elif path.startswith("//"):
            # sqlite:////absolute/path.db -> urlparse(path='//absolute/path.db')
            name = path[1:]
        elif path.startswith("/"):
            # sqlite:///relative/path.db
            name = path[1:]
        else:
            name = path
        return {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": name,
        }

    raise ValueError(f"unsupported_database_scheme:{scheme}")


def _load_env_file(path: Path):
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        k, v = line.split("=", 1)
        key = k.strip()
        val = v.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = val


_load_env_file(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-insecure")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "false").lower() == "true"

_hosts = [
    h.strip()
    for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")
    if h.strip()
]
ALLOWED_HOSTS = _hosts or ["localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "accounts",
    "beacon",
    "api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "beacon_spear.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "beacon_spear.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

default_db = cast(dict[str, Any], DATABASES["default"])

if os.environ.get("DATABASE_URL"):
    DATABASES["default"] = cast(
        dict[str, Any], _parse_database_url(os.environ["DATABASE_URL"])
    )
    default_db = cast(dict[str, Any], DATABASES["default"])

# SQLite is fine for single-process local dev, but this repo runs a web process
# plus a worker process. Add reasonable defaults to reduce "database is locked"
# errors for SQLite-backed dev.
if DATABASES.get("default", {}).get("ENGINE") == "django.db.backends.sqlite3":
    timeout = int(os.environ.get("SQLITE_TIMEOUT_SECONDS", "30"))
    default_db.setdefault("OPTIONS", {})
    cast(dict[str, Any], default_db["OPTIONS"]).setdefault("timeout", timeout)

    try:
        from django.db.backends.signals import connection_created

        def _sqlite_connection_pragmas(sender, connection, **kwargs):
            name = str(connection.settings_dict.get("NAME") or "")
            # Skip in-memory DBs (used by Django test runner).
            if name == ":memory:" or name.startswith("file:memory"):
                return
            try:
                with connection.cursor() as cursor:
                    cursor.execute("PRAGMA journal_mode=WAL;")
                    cursor.execute("PRAGMA synchronous=NORMAL;")
            except Exception:
                # Best-effort: if pragmas fail on a platform/FS, don't block startup.
                return

        connection_created.connect(_sqlite_connection_pragmas)
    except Exception:
        pass


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

AUTH_USER_MODEL = "accounts.User"

TOKEN_HASH_KEY = os.environ.get("TOKEN_HASH_KEY", "")

JWT_SIGNING_KEY = os.environ.get("JWT_SIGNING_KEY", SECRET_KEY)
JWT_ACCESS_TTL_SECONDS = int(os.environ.get("JWT_ACCESS_TTL_SECONDS", "900"))
JWT_REFRESH_TTL_SECONDS = int(os.environ.get("JWT_REFRESH_TTL_SECONDS", "2592000"))

REQUIRE_VERIFIED_EMAIL_FOR_INGEST = (
    os.environ.get("REQUIRE_VERIFIED_EMAIL_FOR_INGEST", "true").lower() == "true"
)
MAX_INGEST_BYTES = int(os.environ.get("MAX_INGEST_BYTES", "1048576"))

DELIVERY_MAX_ATTEMPTS = int(os.environ.get("DELIVERY_MAX_ATTEMPTS", "10"))
DELIVERY_BACKOFF_BASE_SECONDS = int(
    os.environ.get("DELIVERY_BACKOFF_BASE_SECONDS", "5")
)
DELIVERY_BACKOFF_MAX_SECONDS = int(
    os.environ.get("DELIVERY_BACKOFF_MAX_SECONDS", "1800")
)
BARK_REQUEST_TIMEOUT_SECONDS = int(os.environ.get("BARK_REQUEST_TIMEOUT_SECONDS", "5"))

BARK_BLOCK_PRIVATE_NETWORKS = (
    os.environ.get("BARK_BLOCK_PRIVATE_NETWORKS", "true").lower() == "true"
)

NTFY_REQUEST_TIMEOUT_SECONDS = int(os.environ.get("NTFY_REQUEST_TIMEOUT_SECONDS", "5"))
NTFY_BLOCK_PRIVATE_NETWORKS = (
    os.environ.get("NTFY_BLOCK_PRIVATE_NETWORKS", "true").lower() == "true"
)

MQTT_SOCKET_TIMEOUT_SECONDS = int(os.environ.get("MQTT_SOCKET_TIMEOUT_SECONDS", "5"))
MQTT_BLOCK_PRIVATE_NETWORKS = (
    os.environ.get("MQTT_BLOCK_PRIVATE_NETWORKS", "true").lower() == "true"
)

CHANNEL_CONFIG_ENCRYPTION_KEY = os.environ.get("CHANNEL_CONFIG_ENCRYPTION_KEY", "")

EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() == "true"
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "no-reply@localhost"
)
EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
    if EMAIL_HOST
    else "django.core.mail.backends.console.EmailBackend"
)
EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", "10"))

APP_BASE_URL = os.environ.get("NEXT_PUBLIC_BASE_URL", "http://localhost:3000")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "accounts.jwt.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
